name: Manual Test Workflow

# Trigger manually
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run a simple command
      - name: Print Hello World
        run: echo "Hello, World!"

      # Step 3: List files in the repository
      - name: List files
        run: ls -la
